/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as VocabIndexRouteImport } from './routes/vocab.index'
import { Route as VocabIdRouteImport } from './routes/vocab.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabIndexRoute = VocabIndexRouteImport.update({
  id: '/vocab/',
  path: '/vocab/',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabIdRoute = VocabIdRouteImport.update({
  id: '/vocab/$id',
  path: '/vocab/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/vocab/$id': typeof VocabIdRoute
  '/vocab/': typeof VocabIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/vocab/$id': typeof VocabIdRoute
  '/vocab': typeof VocabIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/review': typeof ReviewRoute
  '/vocab/$id': typeof VocabIdRoute
  '/vocab/': typeof VocabIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/progress' | '/review' | '/vocab/$id' | '/vocab/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/progress' | '/review' | '/vocab/$id' | '/vocab'
  id: '__root__' | '/' | '/progress' | '/review' | '/vocab/$id' | '/vocab/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgressRoute: typeof ProgressRoute
  ReviewRoute: typeof ReviewRoute
  VocabIdRoute: typeof VocabIdRoute
  VocabIndexRoute: typeof VocabIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab/': {
      id: '/vocab/'
      path: '/vocab'
      fullPath: '/vocab/'
      preLoaderRoute: typeof VocabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocab/$id': {
      id: '/vocab/$id'
      path: '/vocab/$id'
      fullPath: '/vocab/$id'
      preLoaderRoute: typeof VocabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgressRoute: ProgressRoute,
  ReviewRoute: ReviewRoute,
  VocabIdRoute: VocabIdRoute,
  VocabIndexRoute: VocabIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
